In [1]:
import numpy as np
from numpy.linalg import inv
from sklearn.preprocessing import PolynomialFeatures

Question 3:
(d) Given 𝐲=[0 1]^T, can a unique solution be obtained in dual form? If so, proceed to solve it.


In [2]:
X = np.array([[1,0,1], [1,-1,1]])
y = np.array([0, 1])
print(y)
## Generate polynomial features
order = 3
poly = PolynomialFeatures(order)
P = poly.fit_transform(X)
## dual solution (without ridge)
w_dual = P.T @ inv(P @ P.T) @ y.T
print(w_dual)

[0 1]
[ 0.   0.  -0.1  0.   0.  -0.1  0.   0.1 -0.1  0.   0.  -0.1  0.   0.1
 -0.1  0.  -0.1  0.1 -0.1  0. ]


(d) Given 𝐲=[0 1]^T, can the primal ridge regression be applied to obtain a unique solution? If so, proceed to solve it.

In [3]:
## primal ridge
reg_L = 0.0001*np.identity(P.shape[1])
w_primal_ridge = inv(P.T @ P + reg_L) @ P.T @ y.T
print(w_primal_ridge)

[ 9.99963731e-07  9.99966232e-07 -9.99980001e-02  9.99970894e-07
  9.99969188e-07 -9.99980001e-02  9.99968734e-07  9.99980000e-02
 -9.99980001e-02  9.99973167e-07  9.99969302e-07 -9.99980000e-02
  9.99968165e-07  9.99980001e-02 -9.99980000e-02  9.99969075e-07
 -9.99980001e-02  9.99980000e-02 -9.99980000e-02  9.99967597e-07]


Question 4: Predict the class label for {𝑥 = −0.1} and {𝑥 = 0.4} using linear regression with signum discrimination.

In [40]:
X = np.array([[1,-1], [1,0], [1,0.5], [1,0.3], [1,0.8]])
y = np.array([1, 1, -1, 1, -1])
## Linear regression for classification
w = inv(X.T @ X) @ X.T @ y
print(w)
Xt = np.array([[1,-0.1], [1,0.4]])
y_predict = Xt @ w
print(y_predict)
y_class_predict = np.sign(y_predict)
print(y_class_predict)

[ 0.33333333 -1.11111111]
[ 0.44444444 -0.11111111]
[ 1. -1.]


Question 5: (a) Predict the class label for {𝑥 = −0.1} and {𝑥 = 0.4} based on linear regression towards a one-hot encoded target

In [4]:
X = np.array([[1,-1], [1,0], [1,0.5], [1,0.3], [1,0.8]])
Y = np.array([[1,0,0], [1,0,0], [0,1,0], [0,0,1], [0,1,0]])
## Linear regression for classification
W = inv(X.T @ X) @ X.T @ Y
print(W)
Xt = np.array([[1,-0.1], [1,0.4]])
y_predict = Xt @ W
print(y_predict)
y_class_predict = [[1 if y == max(x) else 0 for y in x] for x in y_predict]
print(y_class_predict)

[[ 0.47798742  0.33333333  0.18867925]
 [-0.64989518  0.55555556  0.09433962]]
[[0.54297694 0.27777778 0.17924528]
 [0.21802935 0.55555556 0.22641509]]
[[1, 0, 0], [0, 1, 0]]


(b) Predict the class label for {𝑥 = −0.1} and {𝑥 = 0.4} using a polynomial model of 5 order and a one-hot encoded target.

In [5]:
## Polynomial regression for classification
## Generate polynomial features
order = 5
poly = PolynomialFeatures(order)
## only the data column (2nd) is needed for generation of polynomial terms
reshaped = X[:,1].reshape(len(X[:,1]),1)
P = poly.fit_transform(reshaped)
reshaped = Xt[:,1].reshape(len(Xt[:,1]),1)
Pt = poly.fit_transform(reshaped)
## dual solution (without ridge)
Wp_dual = P.T @ inv(P @ P.T) @ Y
print(Wp_dual)
yp_predict = Pt @ Wp_dual
print(yp_predict)
yp_class_predict = [[1 if y == max(x) else 0 for y in x] for x in yp_predict ]
print(yp_class_predict)

[[ 1.00000000e+00  1.77635684e-13 -3.41060513e-13]
 [-5.30313768e+00 -3.70234958e+00  9.00548727e+00]
 [ 5.21976232e+00  1.08728407e+01 -1.60926030e+01]
 [ 6.66624941e+00  9.46978846e+00 -1.61360379e+01]
 [-6.47651463e+00 -1.29098961e+01  1.93864107e+01]
 [-2.61986403e+00 -7.80449422e+00  1.04243583e+01]]
[[ 1.57522369  0.46828063 -1.04350432]
 [-0.05207932  0.45436978  0.59770954]]
[[1, 0, 0], [0, 0, 1]]


Question 6: (continued from Q3 of Tutorial 2):
Get the data set “from sklearn.datasets import load_iris”. Use Python to perform the following tasks.

(a) Split the database into two sets: 74% of samples for training, and 26% of samples for testing. Hint: you might want to utilize from sklearn.model_selection import train_test_split for the splitting.

In [6]:
## (a) split data
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

iris_dataset = load_iris()
X_train, X_test, y_train, y_test = train_test_split(
iris_dataset['data'], iris_dataset['target'], test_size=0.26, random_state=0)

In [7]:
y_train

array([1, 2, 0, 2, 0, 0, 1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1,
       0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0, 1, 0, 2, 1, 0, 1, 2, 1, 0,
       2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 1, 2, 2,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1, 0, 2, 0, 2, 0, 0, 2, 0, 2,
       1, 1, 1, 2, 2, 1, 1, 0, 1, 2, 2, 0, 1, 1, 1, 1, 0, 0, 0, 2, 1, 2,
       0])

(b) Construct the target output using one-hot encoding.

In [8]:
# (b) one-hot encoding
Ytr_onehot = list()
for i in y_train:
  letter = [0, 0, 0]
  letter[i] = 1
  Ytr_onehot.append(letter)
Yts_onehot = list()
for i in y_test:
  letter = [0, 0, 0]
  letter[i] = 1
  Yts_onehot.append(letter)

# from sklearn.preprocessing import OneHotEncoder

# onehot_encoder=OneHotEncoder(sparse=False)
# reshaped = y_train.reshape(len(y_train), 1)
# tr_onehot = onehot_encoder.fit_transform(reshaped)
# reshaped = y_test.reshape(len(y_test), 1)
# Yts_onehot = onehot_encoder.fit_transform(reshaped)

In [46]:
reshaped

array([[-0.1],
       [ 0.4]])

(c) Perform a linear regression for classification (without inclusion of ridge, utilizing one-hot encoding for the
learning target) and compute the number of test samples that are classified correctly.

In [9]:
## (c) Linear Classification
w = inv(X_train.T @ X_train) @ X_train.T @ Ytr_onehot
print(w)
# calculate the output based on the estimated w and test input X and then assign to one of the classes based on one hot encoding
yt_est = X_test.dot(w)
yt_cls = [[1 if y == max(x) else 0 for y in x] for x in yt_est ]
print(yt_cls)

[[ 0.11529555  0.20404125 -0.15416052]
 [ 0.21791487 -0.29396894  0.14549901]
 [-0.25363127  0.18246449  0.0362187 ]
 [-0.04023153 -0.58240246  0.57367321]]
[[0, 0, 1], [0, 1, 0], [1, 0, 0], [0, 1, 0], [1, 0, 0], [0, 0, 1], [1, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 0, 0], [0, 0, 1], [0, 0, 1], [1, 0, 0], [1, 0, 0], [0, 0, 1], [1, 0, 0], [1, 0, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [0, 0, 1], [0, 0, 1], [1, 0, 0], [0, 0, 1], [0, 0, 1], [0, 0, 1], [1, 0, 0], [0, 0, 1], [0, 0, 1]]


In [23]:
# compare the predicted y with the ground truth
m1 = np.matrix(Yts_onehot)
m2 = np.matrix(yt_cls)
difference = np.abs(m1 - m2)
print(difference)
# calculate the error rate/accuracy
correct = np.where(~difference.any(axis=1))[0]
print(correct)
# print(~difference.any(axis=1))
# print(np.asarray(~difference.any(axis=1)).nonzero())
accuracy = len(correct)/len(difference)
print(len(correct))
print(accuracy)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 1 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 1 1]
 [0 0 0]
 [0 0 0]
 [0 1 1]
 [0 1 1]
 [0 0 0]
 [0 0 0]
 [0 1 1]
 [0 0 0]
 [0 1 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 1 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 1 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 1 1]
 [0 0 0]
 [0 1 1]
 [0 1 1]]
[ 0  1  2  4  5  6  8  9 12 13 15 17 18 19 20 22 23 24 25 26 27 28 29 30
 32 33 34 36]
28
0.717948717948718


(d) Using the same training and test sets as in above, perform a 2nd order polynomial regression for classification (again, without inclusion of ridge, utilizing one-hot encoding for the learning target) and compute the number of test samples that are classified correctly. Hint: you might want to use from sklearn.preprocessing import PolynomialFeatures for generation of the polynomial
matrix.

In [24]:
## (d) Polynomial Classification
poly = PolynomialFeatures(2)
P = poly.fit_transform(X_train)
Pt = poly.fit_transform(X_test)
if P.shape[0] > P.shape[1]:
  wp = inv(P.T @ P) @ P.T @ Ytr_onehot
else:
  wp = P.T @ inv(P @ P.T) @ Ytr_onehot
print(wp)
yt_est_p = Pt.dot(wp)
yt_cls_p = [[1 if y == max(x) else 0 for y in x] for x in yt_est_p ]
print(yt_cls_p)
m1 = np.matrix(Yts_onehot)
m2 = np.matrix(yt_cls_p)
difference = np.abs(m1 - m2)
print(difference)
correct_p = np.where(~difference.any(axis=1))[0]
accuracy_p = len(correct_p)/len(difference)
print(len(correct_p))
print(accuracy_p)

[[-0.76299101  1.13822047  0.62477054]
 [ 0.6014925  -0.88680328  0.28531078]
 [ 0.59784609 -0.10575032 -0.49209577]
 [-0.85299054  2.07290305 -1.2199125 ]
 [ 0.14176955 -3.06489748  2.92312792]
 [-0.01193797  0.23828328 -0.22634531]
 [-0.12685437 -0.44906348  0.57591784]
 [-0.0345378  -0.02301658  0.05755437]
 [ 0.0405222  -0.19925454  0.15873235]
 [ 0.00558587  0.31463436 -0.32022024]
 [ 0.09555557 -0.10296338  0.00740781]
 [-0.14809056  1.04541241 -0.89732185]
 [ 0.0906437  -0.37729444  0.28665074]
 [-0.07777166  1.0010156  -0.92324394]
 [ 0.12824961 -1.27034815  1.14209854]]
[[0, 0, 1], [0, 1, 0], [1, 0, 0], [0, 0, 1], [1, 0, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 0, 0], [0, 0, 1], [1, 0, 0], [1, 0, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [0, 0, 1], [0, 0, 1], [0, 1, 0], [1, 0, 0], [0, 0,