## Q1

In [2]:
import numpy as np


In [12]:
m_list = [[1,1],[3,4]]

y = np.array([[0],[1]])

X = np.array(m_list)

print(X)

det_X = np.linalg.det(X)
print(det_X)
inv_X = np.linalg.inv(X)
print(inv_X)

# w = inv_X.y
w = inv_X.dot(y)
print(w)

[[1 1]
 [3 4]]
0.9999999999999998
[[ 4. -1.]
 [-3.  1.]]
[[-1.]
 [ 1.]]


### - The <span style="color:blue">np.array()</span> function is used to create an array
### - The <span style="color:blue">np.linalg.inv()</span> function is used to find inverse of a matrix
### - The <span style="color:blue">np.linalg.det()</span> function is used to find determinant of a matrix
### - The <span style="color:blue">dot()</span> function is used to find dot product of two arrays


## Q3

In [19]:
m_list = [[1,2],[2,4],[1,-1]]
y = np.array([[0],[0.1], [1]])
X = np.array(m_list)

tps_X = X.transpose()
print(tps_X)

XTX= tps_X.dot(X)
print(XTX)

det_XTX = np.linalg.det(XTX)
print(det_XTX)

inv_XTX = np.linalg.inv(XTX)
print(inv_XTX)

invXTX_XT= inv_XTX.dot(tps_X)
print(invXTX_XT)

# solution for w

w = invXTX_XT.dot(y)
print(w)

[[ 1  2  1]
 [ 2  4 -1]]
[[ 6  9]
 [ 9 21]]
44.99999999999999
[[ 0.46666667 -0.2       ]
 [-0.2         0.13333333]]
[[ 0.06666667  0.13333333  0.66666667]
 [ 0.06666667  0.13333333 -0.33333333]]
[[ 0.68]
 [-0.32]]


### - The <span style="color:blue">np.transpose()</span> function is used to find the transpose of a matrix


## Q4

In [25]:
# a. Underdetermined System (m<d)
# X is not invertible but we have to chekc if X_XT is invertible

m_list = [[1,0,1,0],[1,-1,1,-1],[1,1,0,0]]
X = np.array(m_list)
y = np.array([[1],[0],[1]])

# Step 1 : Find X Transpose

tps_X = X.transpose()
print(tps_X)
X_XT = X.dot(tps_X)
print(X_XT)

det_XXT = np.linalg.det(X_XT)
print(det_XXT)

inv_XXT = np.linalg.inv(X_XT)
print(inv_XXT)

XT_invXXT = tps_X.dot(inv_XXT)
print(XT_invXXT)

w = XT_invXXT.dot(y)
print(w)

[[ 1  1  1]
 [ 0 -1  1]
 [ 1  1  0]
 [ 0 -1  0]]
[[2 2 1]
 [2 4 0]
 [1 0 2]]
4.0
[[ 2.   -1.   -1.  ]
 [-1.    0.75  0.5 ]
 [-1.    0.5   1.  ]]
[[ 0.    0.25  0.5 ]
 [ 0.   -0.25  0.5 ]
 [ 1.   -0.25 -0.5 ]
 [ 1.   -0.75 -0.5 ]]
[[0.5]
 [0.5]
 [0.5]
 [0.5]]


### Q5

In [27]:
# 5.a - Even 

# 5.b 

m_list = ([1,2],(3,6))
X = np.array(m_list)
det_X = np.linalg.det(X)
print(det_X)

# the determinant is approximately zero so  we can conclude that X is not invertible


#5.c w has no solution

-3.330669073875464e-16


## Q6

In [34]:
#6. Under detemined system since m>d
m_list=[[1,2],[2,4],[1,-1]]
X = np.array(m_list)
y = np.array ([[0],[1]])

tps_X = X.transpose()
print(tps_X)

XTX= tps_X.dot(X)
print(XTX)

det_XTX = np.linalg.det(XTX)
print(det_XTX)

inv_XTX = np.linalg.inv(XTX)
print(inv_XTX)

invXTX_XT= inv_XTX.dot(tps_X)
print(invXTX_XT)

# solution for w
print(y)
w = y.transpose().dot(invXTX_XT)
print(w)

[[ 1  2  1]
 [ 2  4 -1]]
[[ 6  9]
 [ 9 21]]
44.99999999999999
[[ 0.46666667 -0.2       ]
 [-0.2         0.13333333]]
[[ 0.06666667  0.13333333  0.66666667]
 [ 0.06666667  0.13333333 -0.33333333]]
[[0]
 [1]]
[[ 0.06666667  0.13333333 -0.33333333]]


### Q7

In [35]:
m_list=[[2,0,0],[0,0,1]]
X = np.array(m_list)

tps_X = X.transpose()
print(tps_X)

XTX= tps_X.dot(X)
print(XTX)

det_XTX = np.linalg.det(XTX)
print(det_XTX)

## XTX is not invertible since det(XTX) =0 hence no left inverse

[[2 0]
 [0 0]
 [0 1]]
[[4 0 0]
 [0 0 0]
 [0 0 1]]
0.0


## Q8

In [43]:
m_list=[[1,2,3],[4,5,6]]
A = np.array(m_list)
print(A)
# 8.a - Not invertible --> (False)
#8.d  - No Determinant -->( True)
#8e - Since 5.d is true --> (False)

# calculation for left inverse --> AT_A should be invertible
tps_A = A.transpose()
print(tps_A)

ATA= tps_A.dot(A)
print(ATA)

det_ATA = np.linalg.det(ATA)
print(det_ATA)


# 8.b det(XT_X)=0 --> NO Left inverse -->  (False)

#8.c To check for right invertible

A_AT = A. dot(tps_A)
det_AAT = np.linalg.det(A_AT)
print(det_AAT)

#8 d A_AT is invertible --> True

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[17 22 27]
 [22 29 36]
 [27 36 45]]
0.0
54.00000000000001
