In [1]:
import numpy as np

# Question 1

In [2]:
X_1 = np.array([[1, 1], [3, 4]])
y_1 = np.array([[0],[1]])

print(np.linalg.inv(X_1).dot(y_1))

[[-1.]
 [ 1.]]


# Question 2

In [2]:
X_2 = np.array([[1, 2], [3, 6]])
y_2 = np.array([[0], [1]])

print(np.linalg.inv(X_2).dot(y_2))

LinAlgError: Singular matrix

In [4]:
print(np.linalg.det(X_2))

0.0


# Question 3

In [3]:
X_3 = np.array([[1, 2], [2, 4], [1, -1]])
y = np.array([[0], [0.1], [1]])
X_3t = np.transpose(X_3)

print(np.linalg.inv(X_3t.dot(X_3)).dot(X_3t).dot(y))

[[ 0.68]
 [-0.32]]


# Question 4

In [4]:
X_4 = np.array([[1, 0, 1, 0], [1, -1, 1, -1], [1, 1, 0, 0]])
y_4 = np.array([[1], [0], [1]])

X_4t = np.transpose(X_4)

print(X_4t.dot(np.linalg.inv(X_4.dot(X_4t))).dot(y_4))

[[0.5]
 [0.5]
 [0.5]
 [0.5]]


# Question 5

In [7]:
X_5 = np.array([[1, 2], [3, 6]])
y_5 = np.array([[0], [1]])

X_5t = np.transpose(X_5)
print(np.linalg.inv(X_5t).dot(y_5))

LinAlgError: Singular matrix

In [9]:
np.linalg.det(X_5t)

0.0

# Question 6

In [5]:
X_6 = np.array([[1, 2], [2, 4], [1, -1]])
y_6 = np.array([[0], [1]])
X_6t = np.transpose(X_6)
y_6t = np.transpose(y_6)

print(y_6t.dot(np.linalg.inv(X_6t.dot(X_6))).dot(X_6t))

[[ 0.06666667  0.13333333 -0.33333333]]


# Question 7

In [6]:
X_7 = [[2, 0, 0], [0, 0, 1]]
X_7t = np.transpose(X_7)
np.linalg.inv(X_7t.dot(X_7))

LinAlgError: Singular matrix

In [11]:
print(np.linalg.det(X_7t.dot(X_7)))

0.0


# Question 8

In [7]:
A_8 = np.array([[1, 2, 3], [4, 5, 6]])
A_8t = np.transpose(A_8)

print(np.linalg.det(A_8t.dot(A_8)))
print(np.linalg.det(A_8.dot(A_8t)))

np.linalg.det(A_8)

0.0
54.00000000000001


LinAlgError: Last 2 dimensions of the array must be square